### PR TITLE
use native bytes to/from int function where available

### PR DESCRIPTION
**Pull request by ttyridal**
For significant speed gains where available.

### CODE REVIEW

**Comment by ttyridal** [comment]
A little bit of both.  The use case is real time RTP (webrtc client)

**Comment by goncalopp** [comment]
WebRTC in pure python? Wow... Can it handle VP8? Or just audio?
I did a custom client in C a while back, and can remember ICE was a challenge to get right across browsers. Good luck!

**Comment by ttyridal** [comment]
It's more of an experiment to research the protocol(s) and design of webrtc. With a vague goal of a gateway to ip-cameras in the end. So I won't be handling the media compression (Hopefully Google will come around and implement h264 :)).

**Comment by goncalopp** [comment]
That sounds interesting, is it published somewhere?

> So I won't be handling the media compression (Hopefully Google will 
> come around and implement h264 :)). 
Looks like they're working on it :)

**Comment by ttyridal** [comment]
> That sounds interesting, is it published somewhere?

I hope it will be. Right now it's just a pile of vague ideas and experiments.

**Pull request merged**
